---
- hosts: all
  gather_facts: false
  become: yes
  tasks:
        - name: Upgrade all packages
          yum: name=* state=present
          
        - name: Install docker-py with pip workaround for docker-py not installed
          pip: name=docker-py
                      
        - name: Copy Repo to guest  
          copy: src=/vagrant/docker.repo dest=/etc/yum.repos.d/
          
        - name: Copy test script to guest  
          copy: src=/vagrant/test.sh dest=/tmp
          
        - name: Install docker
          yum: name=docker-engine state=present 
          
        - name: Start docker service
          service: name=docker state=started enabled=yes
          notify:
            - Reload systemctl 
        
        - name: Allow vagrant user to run docker commands without sudo
          command: usermod -aG docker vagrant
          
        - name: Build the nginx docker image
          command: docker build -t webnginx:ver1 /vagrant

        - name: Start and run the nginx docker container to serve the static "Hello Word"
          docker:
            name: site
            image: webnginx:ver1
            state: restarted
            volumes:
             - /vagrant/website:/usr/share/nginx/html
            ports:
             - "80:80"          

  handlers:
        - name: Reload systemctl
          command: systemctl daemon-reload 
