---
- hosts: all
  become: yes
  tasks:
        - name: upgrade all packages
          yum: name=* state=present
          
        - name: install docker-py with pip workaround for docker-py not installed
          pip: name=docker-py
                      
        - name: Copy Repo to guest  
          copy: src=/vagrant/docker.repo dest=/etc/yum.repos.d/
          
        - name: install docker
          yum: name=docker-engine state=present 
          
        - name: start docker service
          service: name=docker state=started enabled=yes
          notify:
            - reload systemctl 
        
        - name: allow vagrant user to run docker commands without sudo
          command: usermod -aG docker vagrant
          
        - name: build the nginx docker image
          command: docker build -t webnginx:ver1 /vagrant

        - name: run the docker container to serve the static "Hello Word"
          docker:
            name: site
            image: webnginx:ver1
            state: restarted
            volumes:
             - /vagrant/website:/usr/share/nginx/html
            ports:
             - "80:80"          

  handlers:
        - name: reload systemctl
          command: systemctl daemon-reload 